version: '3.8'
services:
  comment-microservice:
    build:
      context: ./comment
      dockerfile: Dockerfile
    container_name: comment-microservice-container
    ports:
      - "9081:9081"
    networks:
      - comment-mysql-network
      - comment-post-network
      - comment-user-network
  post-microservice:
    build:
      context: ./post
      dockerfile: Dockerfile
    container_name: post-microservice-container
    ports:
      - "9082:9082"
    networks:
      - post-mysql-network
      - comment-post-network
      - post-user-network
  user-microservice:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-microservice-container
    ports:
      - "9083:9083"
    networks:
      - user-mysql-network
      - post-user-network
      - comment-user-network
  mysqldb:
    image: mysql:latest
    container_name: mysqldb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - comment-mysql-network
      - post-mysql-network
      - user-mysql-network

networks:
  comment-mysql-network:
  post-mysql-network:
  user-mysql-network:
  post-user-network:
  comment-user-network:
  comment-post-network:
